#ifndef LIBWHEEL_MACROS_H
#define LIBWHEEL_MACROS_H

#define LIBWHEEL_CONCAT_(x, y)  x##y
#define LIBWHEEL_CONCAT(x, y) LIBWHEEL_CONCAT_(x, y)

#define LIBWHEEL_PREFIX(X)     LIBWHEEL_CONCAT(X, LIBWHEEL_CONCAT(_, LIBWHEEL_ALIAS))
#define LIBWHEEL_DEFINE(X)     LIBWHEEL_CONCAT(LIBWHEEL_NAMESPACE, LIBWHEEL_CONCAT(_, X))

#endif
