#include "wheel/misc/macros.h"

#define vec               LIBWHEEL_APPEND(vec)
#define vec_init          LIBWHEEL_DEFINE(vec, init)
#define vec_with_cap      LIBWHEEL_DEFINE(vec, with_cap)
#define vec_delete        LIBWHEEL_DEFINE(vec, delete)
#define vec_pop           LIBWHEEL_DEFINE(vec, pop)
#define vec_get           LIBWHEEL_DEFINE(vec, get)
#define vec_set           LIBWHEEL_DEFINE(vec, set)
#define vec_grow          LIBWHEEL_DEFINE(vec, grow)
#define vec_foreach       LIBWHEEL_DEFINE(vec, foreach)
#define vec_comparator    LIBWHEEL_DEFINE(vec, comparator)
#define vec_free_type     LIBWHEEL_DEFINE(vec, free_type)
#define vec_map           LIBWHEEL_DEFINE(vec, map)
#define vec_filter        LIBWHEEL_DEFINE(vec, filter)
#define vec_shallow_clone LIBWHEEL_DEFINE(vec, shallow_clone)
#define vec_deep_clone    LIBWHEEL_DEFINE(vec, deep_clone)
