#include "wheel/misc/macros.h"

#define vec               LIBWHEEL_PREFIX(vec)
#define vec_init          LIBWHEEL_PREFIX(vec_init)
#define vec_with_cap      LIBWHEEL_PREFIX(vec_with_cap)
#define vec_delete        LIBWHEEL_PREFIX(vec_delete)
#define vec_pop           LIBWHEEL_PREFIX(vec_pop)
#define vec_get           LIBWHEEL_PREFIX(vec_get)
#define vec_set           LIBWHEEL_PREFIX(vec_set)
#define vec_grow          LIBWHEEL_PREFIX(vec_grow)
#define vec_foreach       LIBWHEEL_PREFIX(vec_foreach)
#define vec_comparator    LIBWHEEL_PREFIX(vec_comparator)
#define vec_free_type     LIBWHEEL_PREFIX(vec_free_type)
#define vec_map           LIBWHEEL_PREFIX(vec_map)
#define vec_filter        LIBWHEEL_PREFIX(vec_filter)
#define vec_shallow_clone LIBWHEEL_PREFIX(vec_shallow_clone)
#define vec_deep_clone    LIBWHEEL_PREFIX(vec_deep_clone)
