#undef vec
#undef vec_init
#undef vec_init_ptr
#undef vec_destroy
#undef vec_destroy_ptr
#undef vec_with_cap
#undef vec_pop
#undef vec_get
#undef vec_get_ptr
#undef vec_set
#undef vec_grow
#undef vec_foreach
#undef vec_comparator
#undef vec_free_type
#undef vec_map
#undef vec_filter
#undef vec_shallow_copy
#undef vec_deep_copy
#undef vec_serialize_json
